# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]
#   schedule:
#     # * はYAMLに置ける特殊文字なので、この文字列は引用符で囲まなければならない、UTCで書く
#     - cron:  '46 2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: before checkout 
#         run: ls -la 
      - uses: actions/checkout@v2
#       - name: after checkout
#         run: ls -la

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo aaaaaaaaa
      - name: テストの実行
        run: | 
          npm install
          npm test

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: テストが失敗したとき
        if: ${{ failure() }}
        run: echo :( test failed
